import { createClient } from "@supabase/supabase-js";
import { projectId, publicAnonKey } from "../utils/supabase/info";

// Use Make's autogenerated Supabase credentials
const supabaseUrl = `https://${projectId}.supabase.co`;
const supabaseAnonKey = publicAnonKey;

// Create Supabase client
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export const isSupabaseConfigured = true;

// Database types
export interface EventData {
  id: string;
  name?: string;
  date?: string;
  venue?: string;
  location?: string;
  revenue?: number;
  attendance?: number;
  tickets_sold?: number;
  [key: string]: any; // Allow for dynamic columns
}

export interface SearchHistoryRecord {
  id: string;
  query: string;
  sql_generated?: string;
  visualization_type?: string;
  created_at: string;
  bookmarked: boolean;
  bookmark_title?: string;
  bookmark_visible: boolean;
}
